import type { Metadata } from "next";
import "./globals.css";


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className="bg-[#f5f5f5] text-zinc-950 antialiased overflow-hidden"
      >
     

        {children}
        
      </body>
    </html>
  );
}
